### ISSUE TITLE
No Connection with NAOqi version 2.8.6.23

### ISSUE THREAD

**Issue by lprobsth** [OpenRoberta/robertalab-naoprogram#1]
I have two robots - one with NAOqi version 2.8.5.10 and one with version 2.8.6.23. The one with the newer version allows no connection.

I tried checking firewall configuration as mentioned in [firewall-network-access-limitation](http://doc.aldebaran.com/2-1/dev/tools/opennao.html#firewall-network-access-limitation). But the program "/etc/init.d/firewall_mode" does not exist.

Did you experience this too?

**Comment by lprobsth** [comment]
From journalctl:
`Feb 16 18:35:35 nao sshd[4314]: Unable to negotiate with [ip address removed] port 38984: no matching key exchange method found. Their offer: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]`

**Comment by lprobsth** [comment]
So I looked up JSch at JCraft and the key exchange methods from the logfile are those supported by JSch. (I tried changing my sshd client configuration with no change to the message in the log - so i wondered where these key exchange methods are defined)

I think the newer configuration in NaoQiOS is responsible for this:
/etc/ssh/sshd_config
```
HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
```

So an option might be changing the sshd configuration file at the robot. But I fear loosing connection to the robot - I'm not an expert when it comes to ssh connections / encryption / keys ...

**Comment by VinArt** [comment]
@chaotic-bruno, hi, as long as you do not remove any auth/kex methods you'll be fine. I think that the naoprogram is using some old kex/auth so it is not there on the robot. You may want to try and add cyphers like 3des-cbc or RC4 to the sshd config and see if that would help, as for kex you can try diffie-hellman-group1-sha1

**Comment by lprobsth** [comment]
@VinArt thank your very much for you reply. I was just yet able to test as I wasn't in our lab since the last few weeks.

Adding methods resolved the issue:

```
KexAlgorithms +diffie-hellman-group-exchange-sha256
MACs +hmac-sha1
```
